# Generated by Django 3.0.2 on 2020-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='year',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
